### ISSUE TITLE
Invalid MIME type used

### ISSUE THREAD

**Issue by iamhuwjones** [cecid/hermes#4]
https://github.com/cecid/hermes/blob/594b2849c4f3290955ee33d02574a1856be212f9/corvus-api/src/main/java/hk/hku/cecid/hermes/api/handler/EbmsSendMessageHandler.java#L152

I believe this should use application/xml or application/octet-stream

**Comment by tomlee** [comment]
According to the [ebMSv2 specification](http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/part2/201004/ebms-v3-part2-cd-01.html)  Section 4.3.1  Behavior of the Sending MSH:

> The `Content-Type` of the data part MUST be set to `application/octet-stream`.

**Comment by tomlee** [comment]
I'll close the issue for now.

**Comment by iamhuwjones** [comment]
Can the issue be reopened? It is not resolved as the code uses an invalid MIME type.

**Comment by tomlee** [comment]
Thanks for your help to fix the bug. Your pull request is merged.
